---
title: "Untitled"
author: "chiwei"
date: "2020/4/1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(googlesheets4)
library(dplyr)
library(tidyverse)
library(lubridate)
library(jsonlite)

```

```{r}
library(googlesheets4)
`出席狀況表單網址` <- "https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

### factor: 類別資料
factor(
  字串向量
)

### POSIXct/POSIXt: 時間資料
ymd_hms(
  字串向量
)

### as.integer()將資料的class轉成integer。由於factor被轉成integer後，其螢幕顯示會顯示電腦是用什麼數字在存這些類別資料
### level_數字與類別文字的對照表mapping table

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)

majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)

majors10_char

majors10_factor

as.integer(majors10_factor) 

levels(majors10_factor)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算

trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
typeof(trueInteger)
trueInteger+2

char3 <- c("小明","1","3")
as.integer(char3)

studentId <- c(410773002, 410773015)
class(studentId)
typeof(studentId)
```
```{r}

```