---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
midtermFilename <- 
  c("exam1-410773888.rmd",
    "exam1410882888.Rmd",
    "410682999第一次期中考.Rmd",
    "期中考310573888.R")

#1
target_regex_1 = "(4|3)([:digit:]+)"
str_extract(midtermFilename,target_regex_1)

#2
target_regex <- "[0-9]{2}"
A_regex <- "[4|3](107|108|106|105|99)"
pattern <- glue::glue("(?<={A_regex}){target_regex}")
str_extract(midtermFilename, pattern)

#3
midtermFilename <- c(midtermFilename,"exam149975013.Rmd","499770121stExam.Rmd")

```

```{r}

jsonlite::fromJSON("https://data.ntpc.gov.tw/od/data/api/EDC3AD26-8AE7-4916-A00B-BC6048D19BF8?$format=json") ->
  garbageRoutes

#1
garbageRoutes$route<-factor(
str_extract(garbageRoutes$linename,"[:alnum:]+路線"))

#2
newlevels<-names(sort(table(garbageRoutes$route)))
levels(garbageRoutes$route)<-newlevels

garbageRoutes$time<-
  str_extract(garbageRoutes$linename,"(?<=線)[:graph:]+")
garbageRoutes$time[is.na(garbageRoutes$time)]<-"全天"
garbageRoutes$time<-factor(garbageRoutes$time)                  

levels(garbageRoutes$time)[[3]]<-"下午"
```

```{r}
jsonlite::fromJSON("https://www.gbyhn.com.tw/blog/post/%E3%80%90%E5%8B%95%E7%89%A9%E6%A3%AE%E5%8F%8B%E6%9C%83%E3%80%91diy%E8%88%87%E6%9D%91%E6%B0%91%E5%80%8B%E6%80%A7%E7%B8%BD%E6%95%B4%E7%90%86%EF%BC%8C%E6%97%A5%E6%9C%ACwiki%E7%BF%BB%E8%AD%AF-%E5%8B%95") -> target


```

